### ISSUE TITLE
Easy Torch Documentation

### ISSUE THREAD

**Issue by manuelarturosantana** [GestaltCogTeam/STEP#1]
Hello!
I say the preprint and I am interested in using this architecture for a problem that I am working on. I figure the easiest way to change it to work on my own problem is to change on of the easy torch files to fit my data. Is there any documentation and an example file explaining in more detail how it works?
Thanks!

**Comment by zezhishao** [comment]
Thanks for your interest!

Easytorch is used to control the training and evaluation process, e.g., building the dataset, building the model, and so on.
The most significant benefit of easytorch is that the designers can focus on the model itself, rather than on other minutiae.
However, what is unfortunate is that easytorch is currently not well documented. 
But you can find the architecture of TSFormer and STEP in 'STEP/models/', which can be transferred to your pipeline.
If you do need to know the details of easytorch, you can put your questions in this issue, and I will answer your questions as soon as possible.
In the next, I will first add documentation for TSFormer and STEP very soon.
Then, we will add detailed documentation for EasyTorch.

**Comment by manuelarturosantana** [comment]
Okay, Thank you!
I do have three other questions.
1. In the DiscreteGraphLearning module there are two layers based on numbers I am unsure where they came from
`self.dim_fc = {"METR-LA": 383552, "PEMS04": 217296, "PEMS-BAY": 217296}[cfg.DATASET_NAME]`
and
` self.dim_fc_mean = {"METR-LA": 16128, "PEMS04": 16128 * 2, "PEMS-BAY": 16128}[cfg.DATASET_NAME]`.
Are both of these model hyperparameters? If so how did you choose them?
2. In my problem I am working with battery data, and have an additional independent variable in addition to time. In each battery cell I want to use time and current to predict voltage and temperature. Is there a straight forward way that I could only forecast voltage and temperature, but not current?
3. In the inputting data for the transformer why is there no dimension for input channels? Should the series be flattened so that instead of being in $\mathbb{R}^{L\times C}$ they are in $\mathbb{R}^{LC}$?
Thank you again!

**Comment by zezhishao** [comment]
1. $\downarrow$
    1.1 `self.dim_fc` is the input dimension of `self.fc`, which is the `FC` used in $G^i=FC(vec(Conv(S^i_{train})))$. Since different datasets have different length training sequence $S^i_{train}$, the dimension of the tensor after $vec(Conv(S^i_{train}))$ (i.e., the `self.dim_fc`) is different. Therefore, maybe debugging is the most convenient way to figure out the number of `self.dim_fc`. 
    1.2 `self.dim_fc` is the input dimension of `self.fc`, which is used as the pooling network applied to the output of TSFormer $H^i$. Therefore, `self.dim_fc_mean=Ld`. For all datasets, `d=96`. For METR-LA and PEMS-BAY datasets, `L=168` (very long-term history over one week), while for PEMS04, `L=168*2` (two weeks).
3. I'm so sorry, I don't understand your research problem well enough to answer it.
4. Actually, they are in $\mathbb{R}^{LC}$. I implement the input embedding layer of TSFormer based on `nn.Conv2d` to transform the space $\mathbb{R}^{L\times C}$ to latent space $\mathbb{R}^{d}$, which is equivalent to applying an FC layer to transform space $\mathbb{R}^{LC}$ to latent space $\mathbb{R}^{d}$. In the current implementation, I do not use any extra channels for TSFormer, since I can not find a clear necessity and significant performance improvement in my datasets.

**Comment by zezhishao** [comment]
1. $\downarrow$
    1.1 `self.dim_fc` is the input dimension of `self.fc`, which is the `FC` used in $G^i=FC(vec(Conv(S^i_{train})))$. Since different datasets have different length training sequence $S^i_{train}$, the dimension of the tensor after $vec(Conv(S^i_{train}))$ (i.e., the `self.dim_fc`) is different. Therefore, maybe debugging is the most convenient way to figure out the number of `self.dim_fc`. 
    1.2 `self.dim_fc_mean` is the input dimension of `self.fc_mean`, which is used as the pooling network applied to the output of TSFormer $H^i$. Therefore, `self.dim_fc_mean=Ld`. For all datasets, `d=96`. For METR-LA and PEMS-BAY datasets, `L=168` (very long-term history over one week), while for PEMS04, `L=168*2` (two weeks).
2. I'm so sorry, I don't understand your research problem well enough to answer it.
3. Actually, they are in $\mathbb{R}^{LC}$. I implement the input embedding layer of TSFormer based on `nn.Conv2d` to transform the space $\mathbb{R}^{L\times C}$ to latent space $\mathbb{R}^{d}$, which is equivalent to applying an FC layer to transform space $\mathbb{R}^{LC}$ to latent space $\mathbb{R}^{d}$. In the current implementation, I do not use any extra channels for TSFormer (i.e., `C=1` for TSFormer), since I can not find a clear necessity and significant performance improvement in my datasets. You can refer to the docstrings of [`_forward_backend`](https://github.com/zezhishao/STEP/blob/9234d1e818d95410e94776798f62fd62b8638c7b/models/TSFormer/model.py#L108) and  [`_forward_pretrain`](https://github.com/zezhishao/STEP/blob/9234d1e818d95410e94776798f62fd62b8638c7b/models/TSFormer/model.py#L42).

Hoping it is helpful to you!

**Comment by manuelarturosantana** [comment]
Yup, thanks!
