### ISSUE TITLE
Question about time-dependent structure learning

### ISSUE THREAD

**Issue by KL4805** [GestaltCogTeam/STEP#29]
Dear authors, 

Thanks very much for your open-source code. I find it very helpful. 

I have a minor question as I go through your code. In the paper, you say that you learn structures jointly with $\mathbf{G}^i$, which is global, and $\mathbf{H}^i$, which is time dependent (Eqn. 2). However, when I go through your code, you comment out the $\mathbf{H}$ part ([link](https://github.com/zezhishao/STEP/blob/ea2c3c3c3b735bc9ace5c7d0a5a27e12cd486cba/step/step_arch/discrete_graph_learning.py#L140)) as you say that it may lead to instability. 

I am curious about it. As training STEP is time-consuming, could you please tell something about the consequences of including time-variant features for learning graph? Thanks for your help.

**Comment by zezhishao** [comment]
Thanks for your question. 
Simply put, adding dynamic features~(i.e., the time-variant features you mentioned) will make the performance drop in most cases (about MAE 2.68@Horizon 3). But by setting different hyper-parameters and learning strategies, sometimes normal results can also be obtained.
I have also been confused by this problem for a long time.
The STEP code has undergone several refactorings, and I'm not sure if the code had this problem at the very beginning (when writing the paper).
Therefore, considering that the dynamic feature is not the main contribution of this paper, I deleted it so that the reader can focus more on the role of the pre-trained model.

**Comment by KL4805** [comment]
Thanks for your timely reply. I come up with similar phenomena when running my own experiments. Your answer was very helpful.
